### ISSUE TITLE
Grammar - End period missing in some alert messages

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/art_show#1]
Per title, some messages are missing the tailing period, whereas others have them. The following messages have been observed with this problem:

"Description is a required field"
"Website is a required field"
"First Name is a required field"
"Last Name is a required field"

Refer to the Google Sheet for details on how to reproduce these messages.

**Comment by kitsuta** [comment]
Those messages are automatically generated in the base plugin. We should probably decide if errors should always have periods or never have periods, and stick with one or the other.
