### ISSUE TITLE
Add Bidder Management Page

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#104]
Like the applications page, but with bidders.
So a menu item that says "Bidders" and then a page that shows a list of the bidders (like the art show applications page does)
From that page, click on a number to go to a bidder detail page, which shows all teh bidder details

**Comment by kitsuta** [comment]
We use a super swanky "DataTables" plugin that lets you sort a table by any of the columns! I'll make bidder number the default. :)
