### ISSUE TITLE
Add an art show operations station view

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#105]
The base view here is maybe a page that has a handful of simple buttons for common art show tasks.
* Check in artist
* Add bidder
* Check out artist 
* Make Sale

We will access this from the art show menu at the top

**Comment by Hugmonster** [comment]
Check in Artist is covered on Issue 106 
Add Bidder - Issue 119 - I will flesh this out more 
Check Out Artist - Issue 120 Needs more details  - Will be very similar to Checking IN an Artist But the status changes will be different.  
Make Sale - Actually scanning and selling the art to the customer.  Two tickets added for this 121 (Bidder Sales)) and 122(Quick Sales)

**Comment by kitsuta** [comment]
Sweet, thank you!
