### ISSUE TITLE
As an art show admin, I want to be able to print bid sheets for the artists

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#118]
This will contain the information from the art entered by the artist in a format that will be compact yet easy to read.
* This should include the bar code for the piece which is a combination of the artist id and piece id.
* printable in groups
* printable in singles

**Comment by Hugmonster** [comment]
NO! We are printing all bid sheets in house.  The Artist will not be printing these at ALL.  
I am working on a bidsheet layout today/tomorrow that will be a single.

**Comment by kitsuta** [comment]
Understood! I'll go ahead and change the title so we don't get confused later.

**Comment by Hugmonster** [comment]
Attached is a Mockup with Data location and a picture of how I would like to print things.  They should look familiar.  

https://docs.google.com/spreadsheets/d/19dK3rhRwnBJFwfgc3f9RssRAI3OyjYQwNJyUh4e43bU/edit?usp=sharing 
[BidSheet Mook UP.xlsx](https://github.com/MidwestFurryFandom/art_show/files/2343849/BidSheet.Mook.UP.xlsx)

Would like this to be size so it can be printed four to a page.  Like the attached image.  
![bidsheetexample](https://user-images.githubusercontent.com/39575926/44962205-a80ffb00-aeea-11e8-9fe3-189a1a44285d.jpg)

**Comment by kitsuta** [comment]
Looks great! Do you know what barcode scanners you'll be using? If not, I'll just pick a 2D barcode (as shown in the mock-up) that's commonly supported.

For the specific info in the barcode, does ARTISTCODE-PIECEID sound right? So it'd be like KIT-1, KIT-2, etc

**Comment by Hugmonster** [comment]
I'll reach out on the scanners previously I have used a simple 2d one.

Yes it should be artist code - piece id

**Comment by kitsuta** [comment]
From our discussion:
Printing bid sheets will be done from the admin view for each artists. We want three options: print a single bid sheet, print a range of bid sheets using their piece ID number, or print all bid sheets for that artist. We'll be having the admin download a PDF in order to better control the look and size of the bid sheets (browsers enjoy doing weird stuff to page margins).

**Comment by Hugmonster** [comment]
Need to add Piece Id (Prefix- ld) above barcode as well.

**Comment by kitsuta** [comment]
Just so I don't forget, in order to get treepoem to generate barcodes I had to run the following commands:
```
docker exec -it quickstart_web_1 /bin/bash
apt-get update
apt-get install ghostscript
```
