### ISSUE TITLE
As an art show staffer, I want to be able to sign up bidders at the event

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#119]
> Bidder sign up at convention:  I want to use the bidders badge to pull up registration information and give them a unique bidder number. 
> I can get a full list of info after the bid sheet mock up.  I DO NOT want to use badge numbers as bidder numbers as I want a sign off that the have read our rules.

**Comment by Hugmonster** [comment]
Attached is the Mock up of the screen.  What I see is an Art Show staffer using the Badge Name to pull information from the Registration database.  ID will be used to confirm correct person has been pulled based on real name.   A safety net for typos or if multiple people have the same badge name.

My intention is for the data to be shown to the Bidder, Update anything that needs to be updated 
 and then we will print to get the signature.  
Can we do a print screen or does it have to go PDF? 

The bidder number is the first letter of the Legal last name and a unique 4 digit number that has not been assigned to anyone else.  For example (N-1234) 
[Bidder Sign Up MOCK UP.xlsx](https://github.com/MidwestFurryFandom/art_show/files/2346367/Bidder.Sign.Up.MOCK.UP.xlsx)

I have emailed legal on the verbiage here as well as the check in sheet and hope that we will not have many changes

**Comment by kitsuta** [comment]
By ID, do you mean an attendee's badge number? I think you do, just want to make sure.

We can indeed open a print dialogue instead of using PDF, and I think that's a fine idea. Probably in general we will default to direct printing, with bidder sheets being the exception because they ought to be a particular size/format.

**Comment by Hugmonster** [comment]
Id I mean something with real name on it.  Driver License etc

**Comment by kitsuta** [comment]
Oh! I see 👍

**Comment by kitsuta** [comment]
Where the Excel file says "Notes," should that be the admin notes that are on the registration, or separate notes for the bidder?

**Comment by Hugmonster** [comment]
Notes  are free text field where we type things like needs early pick up. TN approved.

It would print with everything else
