### ISSUE TITLE
Selling Art via regular silent Auction 

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#121]
Selling all pieces that have been sold to this bidder number.  
This can be done along with Quick Sale items.

Need to total all final sales and add tax. 
Will need to print two receipts one for customer and one for our records.

**Comment by kitsuta** [comment]
What payment processor(s) do you want to use? Does the system need to handle the payment, or is there a separate PoS system you plan on using? Are the receipts just a list of sold pieces along with the price? Do you need the merchant copy to have a line for a signature? Does the system need to record split payments?

For reference, our at the door sales use a VERY basic PoS that simply records the method of payment (Stripe, Square, or Cash). Attendees can't split payments across different methods. If the attendee uses Stripe, the system itself can process that, but if they use Square or Cash we just record the badge was paid for. We need those payment methods so we know where to refund people, but art show might not even need that.

**Comment by kitsuta** [comment]
Oh, and we'll need to think about exactly how we want to let admins add quick sale pieces to the purchase. In order to help avoid mistakes, we probably want to attach the quick sale items to the bidder number before handling payment -- this might be slower, but will help prevent two admins from "selling" the same quick sale piece at the same time.

**Comment by Hugmonster** [comment]
Looks like we will be using Stripe via USB readers for Payment.  (Per emails with Treasurer)  
Possible to split between stripe and cash?  
AKA I walk u and wat to pay $100 in cash and the balance in credit

**Comment by Hugmonster** [comment]
Attaching Quick Sales to an existing bidder should be possible.
Also I will note this on the quicksale ticket that I would like to be able
to do QS without a bidder number (or maybe with a dummy bidder number Like
000)



Hugmonster
Art Show Director

**Comment by kitsuta** [comment]
We should be able to do splits, yes. Probably our best bet is to have a payment workflow where you can specify the amount being paid and the type of payment, record that, and then be brought back to the receipt if there's a balance left. That way it will be flexible enough to handle three-way splits, splits where both payments are with a credit card, etc.

One possible issue is all the printing that will be involved. Computer printers are much slower than PoS receipt printers, at least in my experience. Also, the system will need to do different things if there will be one printer for each sale station vs a single printer for all stations. We don't need to know everything right now -- we can start with just a basic print dialogue -- but those are things we'll need to figure out before the event.

**Comment by Hugmonster** [comment]
Currently I have three printers and 4 workstations.  So we can do almost one to one.

**Comment by kitsuta** [comment]
OK, for now I'll just have it open a print dialogue for the receipts. :+1:

**Comment by Hugmonster** [comment]
[SalesInvoiceMockup.xlsx](https://github.com/MidwestFurryFandom/art_show/files/2520880/SalesInvoiceMockup.xlsx)
The mockup of the invoice for Quicksale and Regular Sale
