### ISSUE TITLE
Applicant can change panel/table values of approved app

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#14]
None of the text fields are updatable, but I was able to change number of panels & tables and save it w/ changes reflected in admin side.

**Comment by jmdawson** [comment]
Corrective action: Those fields should not be updatable in an approved application. In fact, I believe nothing in an approved application should be updatable. Email can handle the expected low volume of requests for after-approval changes.

**Comment by kitsuta** [comment]
Oh right, html attributes like readonly mean nothing to select boxes. :|
