### ISSUE TITLE
Paid state on applications is set to N/A when not paid

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#15]
Should probably be 'no'

**Comment by kitsuta** [comment]
The art show page only show payment status for approved applications. That way when you sort it by payment status, you won't get a bunch of "No" entries for waitlisted applications. It seems to be working as intended on my local box.

If this is about an approved application, or you think it should show if an attendee is unpaid, let me know. :)

**Comment by jmdawson** [comment]
That's probably what I was seeing. It will require some sort of explanation as it's not intuitive.
