### ISSUE TITLE
Bid Sheet Bar code needs to work with Art Show Handheld Scanners

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#156]
![20181016_222841 1](https://user-images.githubusercontent.com/39575926/47058516-6635ce00-d193-11e8-8b8f-7aa0ea15c40c.jpg)
I think we have to shrink location, Artist,  Title and medium to double the height and width of the bar code.   The attached is the manual that comes with the scanner next to our bid sheets.    The Bar code needs to fill the current box at a minimum I think.  I will scan the whole manual in tomorrow.

**Comment by Hugmonster** [comment]
https://www.amazon.com/WoneNice-Barcode-Scanner-Handheld-Reader/dp/B00LE5VV1C/ref=sr_1_1?ie=UTF8&qid=1539743875&sr=8-1&keywords=wn3300  This is the scanners we have

**Comment by kitsuta** [comment]
I'm going to look into an alternative font that works at a smaller size -- the font we're using now needs to be massive to be reliably scanned, it seems. The original font provided was much wider and scanned better at smaller resolutions, but something was wrong with it's encoding.

**Comment by Hugmonster** [comment]
Here is the manual for the scanners we will be using.   
[SKM_454e18101914100.pdf](https://github.com/MidwestFurryFandom/art_show/files/2497076/SKM_454e18101914100.pdf)

**Comment by Hugmonster** [comment]
Closed in Error I cannot seem to reopen it

**Comment by kitsuta** [comment]
This was fixed by https://github.com/MidwestFurryFandom/art_show/pull/204.
