### ISSUE TITLE
As an Admin I need to be able to print an all High bids Report 

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#169]
I need a report that we can place in public sorted by Bidder ID, Piece ID with Piece Name and final Bid or the word AUCTION if a piece is going to Auction.

I would like a line between bidder IDS as in the attached Mock up, but I do not need the boxes around things. That's just to show fields 

[HighBidsReportMockUP.xlsx](https://github.com/MidwestFurryFandom/art_show/files/2531702/HighBidsReportMockUP.xlsx)

**Comment by kitsuta** [comment]
This report implicitly requires changing how close-out works -- there's currently no way for a piece to have a bidder without also being sold to that bidder. For now, this report will just generate the pieces that have actually been won.
