### ISSUE TITLE
As An Admin I need to be able to view and Print a Grand Summary Report 

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#172]
This is a quick summary report. 
See attached Mock up for suggested layout.  
I would like things that can be broken into galleries  but if that is too time consuming we can do it later and just do the main summary numbers. 

Grand Summary Report  - Printed MM/DD/YYYY - HH:MM 			
			
Total Sales 		<Total Sales All> 	
	General	<Total Sales General> 	
	Mature	<Total Sales Mature> 	
			
Total Taxes 		<Total Taxes Collected>	
Tax % Charged		<Tax Percent on File> 	
			
Total Commission 		<Total Commission Collected>	
Commission % Charged 		<Commission Percent on File> 	
			
			
Total Pieces Entered 		<Piece Count All> 	
	General 	<Piece Count General> 	
	Mature 	<Piece Count Mature > 	
			
Total Pieces Sold 		<Piece Count SOLD All> 	
	General 	<Piece Count SOLD General> 	
	Mature 	<Piece Count SOLD Mature > 	
			
Total Piece Sent to Auction 		<Piece Count Auction All> 	
	General 	<Piece Count Auction General> 	
	Mature 	<Piece Count Auction Mature> 	
			
Total Artists 		<Count of all Artists that had pieces in the show> 	
			
Total Panels		<Count of all Panels sold> 	
	General	<Count of General Panels sold> 	
	Mature 	<Count of Mature Panels sold> 	
			
Panel Fee 		<Panel Fee on file>	
Total Panel Fees 		<Count of all Panels sold * Panel Fee> 	
	General	<Count of General Panels sold * Panel Fee>	
	Mature 	<Count of Mature Panels sold * Panel Fee>	
			
			
Total Tables		<Count of all Tables sold> 	
	General	<Count of General Tables sold> 	
	Mature 	<Count of Mature Tables sold> 	
			
Table Fee 		<Table Fee on file>	
Total Table Fees 		<Count of all Tables sold * Table Fee> 	
	General	<Count of General Tables sold * Table Fee>	
	Mature 	<Count of Mature Tables sold * Table Fee>	

[GrandSummaryMockUp.xlsx](https://github.com/MidwestFurryFandom/art_show/files/2531724/GrandSummaryMockUp.xlsx)

**Comment by Hugmonster** [comment]
Commission is 10%  

Assume that anything that is Marked as Auction at some point actually went to auction for the purpose of this count.    If I cannot get if for this year I am fine with skipping it.  I'll have the auction lists I can use.

**Comment by kitsuta** [comment]
Thanks to https://github.com/MidwestFurryFandom/art_show/pull/213 we can now add both the commission and the report of pieces that went to auction.
