### ISSUE TITLE
As an Admin I need an Export (CSV) of Artist Data for Reporting and More

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#175]
I need a CSV or Excel Export of all Artist Data including everything from the Application and Pieces

**Comment by kitsuta** [comment]
Same question as for the bidder report -- what data do you want from their
registration? The registration has a ton of data so including literally
everything would be a bit excessive.

Also if we do a single CSV there will be like 30 columns and half of those
will only use one row so let's go with an Excel sheet instead.

**Comment by Hugmonster** [comment]
OK On further review I would like the following in the report - 
Everything on the Art Show Application form page - https://reg.furfest.org/rams/art_show_admin/form?id=2421afb2-807d-4eb7-bdae-44f9a338641e 
Banner Name 
Also Piece Count Total  ( Pieces will be a different extract. ) 

From Registration: I would Like Badge Name, Email, Phone and address ( Street, City, State, Zip, Country) if we have it,
