### ISSUE TITLE
As an Admin I need an Export (CSV) of Bidder Data for Reporting and More

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#176]
I need a CSV or Excel export of all Bidder data that was collected as part of the Bidder signup

**Comment by kitsuta** [comment]
What registration data would this include? Currently bidders themselves
have very little information -- just the hotel, room number, and notes.
Everything else is on the registration.

Should the CSV include all the fields that are currently on the bidder sign
up page?

**Comment by Hugmonster** [comment]
Yes please.  At  a minimum I need real name and Badge Name
