### ISSUE TITLE
Checking in an Artist and the City is still a drop down.  

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#198]
Artist - Nine Elevenzies

Got pop up to select a state and choose Ohio .  Choose Save and Check in and it not displaying the state selected.

It looks like it has saved somewhere as it shows when I go back into the artist application, Pieces and print the checkin from there

**Comment by kitsuta** [comment]
I cannot reproduce this on my local server, but I can reproduce it on staging.

**Comment by kitsuta** [comment]
Fixed by https://github.com/MidwestFurryFandom/art_show/pull/210. Thank goodness.
