### ISSUE TITLE
As an Admin I would like to print the Check in form when Saving and Checking in an Artist 

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#199]
The form that prints on save and check in is not the check in form that prints when you print from the pieces sheet.  http://rams.test.furfest.org/rams/art_show_admin/pieces?id=7802ce7d-80c0-4247-bf00-26e735ffa0a2  

The attached is what prints - 
![checkinformprint](https://user-images.githubusercontent.com/39575926/48288800-4d8ba180-e43b-11e8-808c-5498e3cf7f51.JPG)

**Comment by kitsuta** [comment]
![image](https://user-images.githubusercontent.com/7198215/48382330-854e4f80-e6ae-11e8-9592-c9f0e06ae23f.png)
Attached is what prints on my local server.

Oddly, I tried to reproduce on staging and nothing printed at all.
