### ISSUE TITLE
Is "Panels" adequately descriptive?

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#20]
This is best if feedback from the customer (Nall, Allison) but we may have to guess ourselves: Is the description of selection options (Panels, Tables) adequately clear to the intended users? I think that most art show applicants would be aware of what to expect, and the art show rules should specify this information, but is there a way we can make the options more intuitive, especially w/ an eye towards applicants w/ less experience?

**Comment by Hugmonster** [comment]
It is descriptive enough.  I've dealt with everyone from first timers to pros.
