### ISSUE TITLE
As an art show admin, I'd like to add an artist's mailing country and region on the pieces page

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/art_show#201]
On the art_show_admin/pieces page, there's a form for adding or editing the artist's mailing address, assuming that the artist has chosen to mail in their pieces. However, on this page _only_, and _only_ if the mailing address is not already set, it is not possible to fill in the country or state/region -- regardless of what is entered, they both get set back to empty fields.

The best way to reproduce this is to:
1. Use the admin interface (art_show_admin/form) to create an approved artist application with "I'm mailing in my art" selected.
2. Click the "Submitted Pieces" link on the top row of links.
3. Add a mailing address.
4. Click the "Update Info" button and observe that the country and state are not saved. State/region actually appears to clear _before_ the form submits.

**Comment by jmdawson** [comment]
@kitsuta Sounds like we can get away with fixing this in the first iteration after launch

**Comment by kitsuta** [comment]
Yea, the pieces page is shown later in the process. It was the US-only checkbox that needed to go live before applications opened, this just got lumped in together with that.

**Comment by jmdawson** [comment]
Ok I'll guess it at October.

**Comment by Hugmonster** [comment]
Please.  Seeing the Country  and region on the pieces page helps with other issues.

**Comment by jmdawson** [comment]
@Hugmonster Please confirm this is fixed, or else create a new ticket in /rams

**Comment by jmdawson** [comment]
https://github.com/MidwestFurryFandom/rams/issues/457
