### ISSUE TITLE
Registration Confirmation feature appears non-functional

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#21]
This is a currently-valid, complete badge: 78e13c56-18ce-43c3-aa3b-930cf1c8530b

However, entering that number returns a message that it is not a valid confirmation number.

**Comment by kitsuta** [comment]
I can't reproduce this bug; I just filed an art show application by copying and pasting that number into the confirmation ID field.

**Comment by jmdawson** [comment]
I can't reproduce it on staging, either, so who knows anymore?
