### ISSUE TITLE
As a web app with terrible JS optimization, I would like a serverside search bar to limit artists loaded on the artist check-in/out page

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/art_show#215]
We've already had one difficult-to-track-down bug (https://github.com/MidwestFurryFandom/art_show/issues/198) that is related to the artist check in/out page's load time, proving that the current design of the page is just too brittle and dependent on data size. I've also seen a UX bug (unfiled) involved in the interaction between the DataTables plugin and the check-in/out page's modals -- if you use DataTables to filter artists and then refresh the page, artists that aren't in the filter don't have modals.

We've finished everything else pretty early and under budget (yes, all issues in the milestone are either closed or have pending PRs!) we should be able to spare some time to fix this page up. We'll make it function like the bidder sign-up page, which has a serverside search bar. This is much preferable to risking a constant stream of time-consuming JS bugs from this page.

We'll also change this page's form-printing behavior to help track down and fix https://github.com/MidwestFurryFandom/art_show/issues/199.

**Comment by jmdawson** [comment]
Sounds reasonable.
