### ISSUE TITLE
Production Logins needed for Art Show staff 

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#223]
Please create logins for all of my staff for the Art Show to access the Art Show parts of Rams 

Please give the folllowing AD's the same rights as me: 
Jim Hayter, Kevin Corcoran,  and Erik Noble

**Comment by kitsuta** [comment]
I don't have access to prod. This might go in JIRA better?

**Comment by jmdawson** [comment]
This is for me. And yeah maybe it's a servicedesk ticket but whatever at this poitn.

**Comment by Hugmonster** [comment]
I can move it there and close this one?

**Comment by jmdawson** [comment]
Go ahead and submit a ServiceDesk ticket so it's documented in the same place as all the other 2018 work in other departments.
