### ISSUE TITLE
Admin: User must use back button to cancel adding new app

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/art_show#23]
Unlike when editing an existing application, when creating a new application there is no built-in button/link to cancel/return to the search list. Using a browser's back button still works.

**Comment by jmdawson** [comment]
Not sure what's going on here. Adding an attendee as an admin, I see those buttons. Adding from the attendee side, there shouldn't be any back buttons. Attendees should be directed to the application directly, and then their transaction will be complete and they should close the tab.

**Comment by jmdawson** [comment]
Oh, cancel adding a new app.

**Comment by jmdawson** [comment]
Adding a new attendee does not have a cancel button, either. For consistency, I do not believe we should add one in this app at this time.

 Later, perhaps, we could rework all those pages to be consistent and have a cancel button.
