### ISSUE TITLE
As an art show director, I'd like a way to add arbitrary money to the artist invoice

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/art_show#236]
Right now, the only way to change an artist's invoice is to "sell" their pieces in the system, but in certain cases we want to give money to the artist for other reasons. Art show staff should be able to add an arbitrary amount of money (with cents!) along with a reason, and both of those should be their own table on the artist's invoice.

**Comment by Hugmonster** [comment]
I'd like to talk about this before it gets added.   I think I remember the why, but legalities say we cannot give them donations

**Comment by Hugmonster** [comment]
Discussed with Legal and the Accounting.  We CANNOT do this.  I will instruct my team when they get this to suggest checking the artist posted information to see if they have a tips option on there personal site.
