### ISSUE TITLE
Admin: Column sort icons are not visually grouped with columns they sort

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/art_show#24]
See image for example. Note how the sorting arrow appears to be associated with Art Show Cost, when in actuality it is for the column to the left (Tables).

![image](https://user-images.githubusercontent.com/28108495/31477029-46c946ec-aecf-11e7-963f-d28f2797ba48.png)

**Comment by kitsuta** [comment]
This is part of the DataTables plugin. If we want to change the alignment, we can change that plugin's CSS (https://stackoverflow.com/questions/28575810/jquery-datatables-left-align-sort-icon)

**Comment by jmdawson** [comment]
We can fix this when a user complains. Given that I can click on the label and get the behavior I want, I can only hope they'll figure it out. This would probably be clearer if there was more of a border (any border) between cells.
