### ISSUE TITLE
As the art show director, I'd like an email automatically sent to Mail In Artists on a set date before the convention

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/art_show#240]
Need to automatically send an email to Mail In artists that are approved with instructions as to whom to send to and other instructions.

We'll need to get the text for this email and subject line for this email.

**Comment by Hugmonster** [comment]
Will add template soon, But title needs to be changed.  I want an email to go to all mail in artists with instructions on a set date before the convention, not upon approval as I do not want this lost by the artists.

**Comment by Hugmonster** [comment]
Subject: MFF Art Show MAIL IN Instructions 
Date to Send:   November 1, Noon  latest October 25, Noon prefered (AKA About a month before deadline) 
Template attached 
[MailInTemplateWithAddress.docx](https://github.com/MidwestFurryFandom/art_show/files/3598534/MailInTemplateWithAddress.docx)

**Comment by Hugmonster** [comment]
https://drive.google.com/file/d/0B47DKkM7hYhvbTFZdFdWWUtaUzZJNXBkLVNTU1Q5bWtUU0I0/view?usp=sharing   In case the above document is corrupt .

**Comment by Hugmonster** [comment]
Will this be happening in the next few days or should I plan on doing it manually as I did last year?

**Comment by jmdawson** [comment]
It looks like this didn't get into Sprint 3. It was probably intended for Sprint 4, but that slipped a month.

@DarkKilauea  @kitsuta Is this something we can sneak into the remainder of Sprint 3?

**Comment by kitsuta** [comment]
Whoops, a bit late on this but I should be able to squeeze it in today. 0.5 hour estimation.

**Comment by jmdawson** [comment]
@kitsuta  This probably needs a pair of variables, based on Trish's feedback. Or it needs to be based off of some other date.

**Comment by Hugmonster** [comment]
The date emails generated for Midwest FurFest Art Show MAIL IN Instructions shows between Nov 8 and Dec 8.   I need that changed to Oct 25 and Nov 27

**Comment by jmdawson** [comment]
It's not currently a set date, it's currently "30 days before the art show deadline." So either we need to make the number of days configurable and base it on...the epoch/eschaton, or possibly we just need to be able to spec the mail in email start and end dates.

**Comment by Hugmonster** [comment]
If it needs to be based of the Art show end date than I would like this to be 40 days ahead of that date.   Thought process is that all mail in art should reach us one week before convention, So I am warning them of that dead line more than 30 days before convention, but less than 60 so the information does not get lost

**Comment by kitsuta** [comment]
Whoops! I would have sworn that the dates I set for that email would have put it in the right timeframe -- I must have miscalculated. I'll set it up to send 40 days ahead of the deadline. The only major thing is, the email categories (database model AutomatedEmail, _not_ Email) need to be cleared from the database to update the date. It's safe to clear the email categories, the system just looks at the code and sets them up again after a few minutes.

**Comment by kitsuta** [comment]
Confirmed that we got this sent out. :+1:
