### ISSUE TITLE
As the Art Show Director, I'd like an email automatically sent to artists that selected that they have an agent, but haven't assigned one as of a cut off date

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/art_show#241]
We need to automatically send an email to artists that have selected agent but do not have one assigned as of a cut of date.

We'll need to get details from the Art Show department as to the text and subject line of the email as well as the cutoff date that should be used.

**Comment by Hugmonster** [comment]
Email send date is 11-1-2019 Noon 

Subject Line:  MFF Art Show Application MISSING AGENT
Template is attached please note the *word*   That specify
[ArtistMissingAgent.docx](https://github.com/MidwestFurryFandom/art_show/files/3598376/ArtistMissingAgent.docx)
 where data should be added from Rams

**Comment by Hugmonster** [comment]
Email seems to be missing a criteria check as it went to 79 people not just the ~5 folks that have chosen "I'm appointing an agent"  and do not have one linked.  I have unapproved the email and we will just need to put this on the list of things to fix before it is needed next year

**Comment by kitsuta** [comment]
You're right, there is a bug/oversight in that email and we didn't catch it. ☹️ I will fix this for no cost, I'm sorry we found the bug the hard way.
