### ISSUE TITLE
As the Art Show Director, I need a way to do mass entry of artist locations

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/art_show#242]
The screen should have the ability to enter the following information:

- Artist Name
- Artist's Real Name
- Number of Grids and Tables per section
- Location

**Comment by Hugmonster** [comment]
I need this screen to pull a list of all approved artists with 
Artist Name
Real Name 
Number of Grids by section  
Number of Table by section 

I would enter the locations  ie:   T1-2, MA1-2, RG1-2  
Will add a template to clear up
