### ISSUE TITLE
As an Art Show staffer, I need to check for duplicates only against pieces for the same artist

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/art_show#243]
This is probably related to #135 

The check for duplicates should only check against pieces by the same artist code, not all piece names.

**Comment by Hugmonster** [comment]
Correct.

**Comment by Hugmonster** [comment]
Duplicates names are not being caught  
http://rams.test.furfest.org/rams/art_show_applications/edit?id=f01b3ac2-f5c6-42ff-825e-4edd6a6f7177
![DuplicateCheck](https://user-images.githubusercontent.com/39575926/66730317-e7638780-ee1e-11e9-929d-6bd19e8d4dc5.PNG)

**Comment by kitsuta** [comment]
Turns out, I'd made this check work correctly when _editing_ piece names but not when _adding_ pieces. Should be fixed in the next round of updates.
