### ISSUE TITLE
As an Art Show staffer, I'd like the Artist Check In form adjusted to show the status of all pieces by the artist

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/art_show#244]
The check in form should show the status of all pieces and allow sorting by Piece Id.

**Comment by kitsuta** [comment]
The check-in form already _does_ show the status of all the artist's pieces, so I'm not sure what's needed for this and #245 except to enable sorting.
![image](https://user-images.githubusercontent.com/7198215/63640321-afd12e00-c66c-11e9-8003-37e3c4dbe8f6.png)

**Comment by Hugmonster** [comment]
The issue is the status does not show when we print these forms.  At least that is my memory.  I will test

**Comment by Hugmonster** [comment]
Error on clicking print check in form from artist application 
http://rams.test.furfest.org/rams/art_show_applications/edit?id=4b535f1a-3b33-4e98-8489-aeffe03bd674

http://rams.test.furfest.org/rams/art_show_applications/print_check_in_out_form

Sorry, page not found!

404 Not Found
The path '/rams/art_show_applications/print_check_in_out_form' was not found.    

Works fine from admin side.  I need this to work for sign off from Mail in Artists
