### ISSUE TITLE
As an artist, I should only be able to select the section that I've purchased when entering a piece

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/art_show#246]
From Hugmonster: "I would like folks to only be able to select the section (Mature/General) that they have purchased during piece entry"

**Comment by kitsuta** [comment]
While doing this, we could also allow artists to select between mature table, mature panel, general table, and general panel by changing it from a toggle button to a dropdown. Would this be good, or is that information not particularly valuable ahead of time?

**Comment by Hugmonster** [comment]
I just need the basic this item is in Mature/General.  Having table vrs grid would be helpful but not necessary in the long run.
