### ISSUE TITLE
Piece name flows into the minimum bid space on the Bid Sheet when the piece name is too long

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/art_show#248]
Maybe we should truncate the piece name if it is too long?

**Comment by kitsuta** [comment]
We actually do have a maximum length for piece names (`piece_name_length`) -- currently it's 50 characters long but it can be shorter. I believe what happened last year is that a limit was requested and added _after_ a lot of artists had put in their pieces, so several pieces were over the limit.

**Comment by DarkKilauea** [comment]
In that case, let's do a quick test to verify that the new limit doesn't cause any problems with the produced bid sheet, then close the ticket if everything is fine.

@SkylerRingtail Would you be willing to test this during your pass on the other Art Show functionality?

**Comment by Hugmonster** [comment]
I verified we fixed this along the way and it is no longer an issue.  Closing the ticket.
