### ISSUE TITLE
Admin: Consider adding confirmation warning when changing application status

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/art_show#26]
Because we send the attendee an email when changing their application status, we may want to consider adding a popup confirmation dialogue when the user attempts to save a status change. Because we can't pull back the sent email if we made the wrong change to status, it seems it would be worth adding an "Are you sure?" step.

**Comment by jmdawson** [comment]
We can consider this further, but Dealers does not do this, and I did not receive any complaints from Brendan about unintentionally approved dealers. Given that this will add extra clicks to each approval, I think we should wait to consider this until the users complain.
