### ISSUE TITLE
Missing pay button on application screen

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/art_show#267]
If someone registers for the convention thru the art show application
after they are approved the button to pay does not appear on the
application page.

![NoPayButton](https://user-images.githubusercontent.com/1929107/66258862-faab8e80-e75e-11e9-9334-6620f291574b.PNG)
Is a good example.

Artist was not yet registered, Admin approved, Artist reopened
application, used link to register for con and has no pay button on
the application screen.

**Comment by DarkKilauea** [comment]
![NoPayButton](https://user-images.githubusercontent.com/1929107/66258862-faab8e80-e75e-11e9-9334-6620f291574b.PNG)

**Comment by kitsuta** [comment]
It states at the top of the page that they need to finish filling out their badge information. This is because they haven't entered any of the info MFF requires for a badge, just their name and email. We can make it a button instead of a link?

**Comment by Hugmonster** [comment]
No I filled in all the details.  If I click on the link I get a message
about being able to update the data.

**Comment by kitsuta** [comment]
Ah, you're right, the information is filled in! That template needs looking at, then.

**Comment by Hugmonster** [comment]
Still NO pay button.. but they can enter pieces  ;)
http://rams.test.furfest.org/rams/art_show_applications/edit?id=29fa67ca-35b3-4517-98e6-76a34be825bb


http://rams.test.furfest.org/rams/art_show_admin/form?id=29fa67ca-35b3-4517-98e6-76a34be825bb

shows them as not paid...

**Comment by kitsuta** [comment]
Fixed in https://github.com/MidwestFurryFandom/mff-rams-plugin/pull/172

**Comment by kitsuta** [comment]
Looks like this is working now. :+1:
