### ISSUE TITLE
Paid artists are no longer being taken to the screen to enter piece information after payment

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/art_show#268]
Paid artists of all types are no longer being taken to the screen to
enter piece data after paying for the space -
Getting only this page:
![1PaidNoPieces](https://user-images.githubusercontent.com/1929107/66258878-27f83c80-e75f-11e9-89f0-9fd4d45f03b4.PNG)

Instead of:
![2PaidReadytoEnter](https://user-images.githubusercontent.com/1929107/66258882-30e90e00-e75f-11e9-8605-a65cc078399b.PNG)

**Comment by kitsuta** [comment]
Whoops, that's an oversight in that template. Super easy to fix.

**Comment by kitsuta** [comment]
This should be fixed in the next round of updates.

**Comment by kitsuta** [comment]
Fixed. :+1:
