### ISSUE TITLE
Confirm Fixed: Mail In Address Collection Window showing again

### ISSUE THREAD

**Issue by DarkKilauea** [MidwestFurryFandom/art_show#269]
Something in recent changes has brought back a view we previously
killled on https://github.com/MidwestFurryFandom/art_show/issues/89

I know this page was not showing earlier as other Mail in artists have
successfully paid.

The issue is the page will not allow a state to be chosen.  We have
had this issue in the past and removed the page as it was unneeded.

Issue exists in User and Production and is preventing an artist from paying.
I know that this did not exist before go live as I tested all types of
artists soup to nuts.

**Comment by kitsuta** [comment]
This should be working as expected with the next round of updates. Technically it should be working now, but there's another bug related to this page that I've fixed in code.

**Comment by kitsuta** [comment]
Huh, it appears we do still show the mail address form for mail-in artists... it's just that they can also add pieces without filling in their info.

In any case the state dropdown issue has been fixed, so it should no longer prevent artists from doing anything.
