### ISSUE TITLE
Orphaned art show applications throw a 500 error

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/art_show#282]
While it's incredibly rare to do so, theoretically you should be able to unlink an art show application from an attendee. However, after this is done the application's form throws a 500 error.

The issue is this property: https://github.com/MidwestFurryFandom/art_show/blob/mff-staging/art_show/models.py#L265 -- it assumes that the app has an attendee. We just need to tweak the property to account for cases where the app doesn't have an attendee associated with it.

Unfortunately there's no workaround in the system, though you can use the database to manually set a new attendee_id.

**Comment by Hugmonster** [comment]
Occurs when registration cancels an attendee.  Needs to be cleaner in the future.  Registration changes might resolve this?
