### ISSUE TITLE
Some art show pieces did not get paid status after being paid

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#293]
GOL-2 (fefd4ae6-9a63-4284-b026-bb3a9761e609) and DIA-7 (fe961a5c-3a38-4a31-a3b7-d58de03f8cb0) both ended up w/ sold (107404813) status even though they have associated receipts and other pieces on those receipts are listed as paid (110959155)

**Comment by Hugmonster** [comment]
Only happen with one piece and I think it was affected by changes in process, possibly multi work stations had same item open.

**Comment by jmdawson** [comment]
https://github.com/MidwestFurryFandom/rams/issues/455
