### ISSUE TITLE
Don't show the "art show link" snippet on the prereg page

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/art_show#33]
Seeing this while buying a badge is honestly a little silly:
![image](https://user-images.githubusercontent.com/7198215/31853807-1d23a6a8-b65d-11e7-9d04-7d1f0c83a673.png)

@jmdawson whenever it's convenient, can you let me know if the art show folks want the prereg page to still link to the app in some format? I.e., should this be removed wholesale or just reworded?

**Comment by jmdawson** [comment]
I think someone complained about it at the meeting. Let's just pull it out.
