### ISSUE TITLE
No MFF contact email listed on post-registration  page

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/art_show#4]
This might just be missing in our dev build, but we should remember to add a contact email to the post-registration page. We currently mention an artshow contact email on that page, but none is listed.

**Comment by kitsuta** [comment]
Seconded; none of the templates are written to accommodate a missing email address for the art show, so you get weird strings like "Contact us via  to request more than 4 panels." The config option is `art_show_email`.

**Comment by jmdawson** [comment]
That has already been applied on staging.
