### ISSUE TITLE
base_price does not update correctly

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#41]
Base price is not updated after application is made. If admin changes allocation to, say, 4 panels, when app was made at 2, base_price will still reflect $10.

**Comment by SkylerRingtail** [comment]
Only recalculates after saving and refreshing (field is not dynamic). Consider making field dynamic, if we have the time.

**Comment by jmdawson** [comment]
Dynamism in this field would be a separate issue under the 2018 tag.
