### ISSUE TITLE
Admin: Notification box obscures navigation bar, and does not auto-close

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/art_show#46]
Our banner notification box obscures the navigation menus on the admin side of things, and does not automatically close (or at least does not do so in a reasonable length of time). While the user can click to close the message, this is an extra (and in my opinion unnecessary) click.

Can we add a timer to automatically fade out and close the message box after, say, 10 seconds?

**Comment by jmdawson** [comment]
This has been a lingering RAMS issue since it was bootstrap-enabled. We should see if MAG has fixed this in their branch. It annoys me regularly, too. However, it's also tolerable enough to make this a 2018 item.

**Comment by kitsuta** [comment]
Still not fixed for MAGFest, but definitely on the wishlist.

The problem with just adding a timer is that the same KIND of messaging popup is used everywhere, including for important messages that shouldn't fade out after 10 seconds. The whole thing needs an overhaul, which coincidentally is also why it hasn't been done yet.
