### ISSUE TITLE
Link to email on Art Show application Confirmation Screen

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#61]
![image](https://user-images.githubusercontent.com/39575926/40460976-3700b5e8-5ed7-11e8-8518-64f7ecbfe6d7.png)

Link from Here goes to registration.  Please remove that link.  They can edit the application to see the email provided on it.

**Comment by jmdawson** [comment]
Would you like that line removed outright?

**Comment by jmdawson** [comment]
A more complicated line can wait until a later iteration. I'll remove the line and call it good enough.

**Comment by Hugmonster** [comment]
Works

**Comment by Hugmonster** [comment]
Not sure what happen as this has more text now than it did originally.  See original screen shot.  

Unless this is text that only occurs when they are attending...

**Comment by jmdawson** [comment]
Added paragraph up top is what happens when you also apply for a badge during the process.
