### ISSUE TITLE
Agent not chosen at registration 

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#64]
I need them to choose an agent when they attempt to register not give an agent a code.   You will end up with multiple people giving one agent multiple codes.  

http://rams.test.furfest.org/rams/art_show_applications/edit?id=9e0ed4cf-a53e-4dda-be0e-8ba173a6675e

![image](https://user-images.githubusercontent.com/39575926/40520550-c9174452-5f94-11e8-92eb-d0ac62a36562.png)

**Comment by kitsuta** [comment]
Yup, as far as the system is concerned there's one agent per app but a person can agent for multiple apps. You can't enter all the codes during pre-reg but you can add them via your confirmation page. The agent's page will list the art show apps that they're tied to.

**Comment by Hugmonster** [comment]
I think I need rams 101.

On May 24, 2018 9:36 PM, "Victoria Earl" <notifications@github.com> wrote:

Yup, as far as the system is concerned there's one agent per app but a
person can agent for multiple apps. You can't enter all the codes during
pre-reg but you can add them via your confirmation page. The agent's page
will list the art show apps that they're tied to.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MidwestFurryFandom/art_show/issues/64#issuecomment-391915076>,
or mute the thread

**Comment by Hugmonster** [comment]
I'm fine with how this was resolved and think this ticket can be closed.
