### ISSUE TITLE
Send agent code in artist reg email

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#65]
If artist specifies they'll use an agent in their application, include their agent code in their application confirmation email.

**Comment by kitsuta** [comment]
This was actually a bug! It was coded up to include the agent code, but the email was being sent before the code was generated. Emails now look like this:
![image](https://user-images.githubusercontent.com/7198215/41737912-a8522c20-755e-11e8-935a-15474c9125bb.png)

Look good?
