### ISSUE TITLE
Add art_show_reg_start

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#68]
Dealers has a reg start date, but art show doesn't. Let's add a feature for setting the start date: great for opening art show at a later date than pre-reg.

**Comment by kitsuta** [comment]
Attendees will now see these pages if they visit the art show before it starts or after it ends:

![image](https://user-images.githubusercontent.com/7198215/40579977-e35cb09e-6102-11e8-8c54-dbf0706db218.png)
![image](https://user-images.githubusercontent.com/7198215/40579979-fdfcdffa-6102-11e8-81b7-18345426fb15.png)

Does that look good?

**Comment by jmdawson** [comment]
I think we can leave out the month. It looks awkward because it seems to be based on the start date.  Alternately, we could put the start - end dates.

**Comment by jmdawson** [comment]
Final decision: Leave out the month. Thus "Art show applications for Midwest Furfest 2018 are not yet open."
