### ISSUE TITLE
Website field should be optional

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#7]
From the user: Website doesn't need to be a required field nor even on the page, artists bring business cards for this

I think the user is misunderstanding the purpose of the form. I would make it optional in case the artist wishes to provide the link so we can inspect it during the approval process.

**Comment by kitsuta** [comment]
Fixed by https://github.com/MidwestFurryFandom/art_show/commit/b3535693bf309c204134bf396f95877c7b902c22.
