### ISSUE TITLE
Non-attending artist seems to be greeted w/ a "Thank you for upgrading your badge" screen

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#83]
Maybe nobody cared last year, but it's not quite right. Price correctly represents number of panels, at least.
<img width="837" alt="screen shot 2018-06-26 at 22 41 59" src="https://user-images.githubusercontent.com/910490/41951804-4c88b750-7992-11e8-881c-9ada273a986e.png">

**Comment by kitsuta** [comment]
It looks like the intended workflow is to go to the app's edit page, given that's where the payment link on the admin page goes to. I can't seem to make it trigger a payment properly, though.

**Comment by kitsuta** [comment]
OK, further investigation shows that I broke this when I added the mailing address form to the application. The changes in https://github.com/MidwestFurryFandom/art_show/pull/91 fix it so the payment button shows up correctly.
