### ISSUE TITLE
Total Price not updated in app change email

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#87]
<img width="741" alt="screen shot 2018-06-27 at 16 04 07" src="https://user-images.githubusercontent.com/910490/41999647-cf925002-7a23-11e8-89ee-c5e7a1136a35.png">
<img width="650" alt="screen shot 2018-06-27 at 16 03 56" src="https://user-images.githubusercontent.com/910490/41999641-cc97c74c-7a23-11e8-84d8-9f114e9c3fce.png">

On the app itself, it's correct, but for some reason in the email, the total price is still the old price.

**Comment by jmdawson** [comment]
app.potential cost it the value in that field

**Comment by Hugmonster** [comment]
Noticed another issue tied to this.  If they chnage from say a Mail in to Attending or Agent the other flags do not get picked up.   For example - I Made Test10B from Mail in to Agent and they got the updated email but no agent Id

**Comment by kitsuta** [comment]
There's no agent code section in the app change notification, looks like we'll need to add it.

**Comment by jmdawson** [comment]
Yes there is. I put it in recently.

**Comment by kitsuta** [comment]
... I REALLY gotta remember to browse the mff-staging branch on web GitHub.

In that case, that problem should be fixed by #88 as well, since that PR forces a DB update before the app change email gets sent.
