### ISSUE TITLE
Artist using Agent cannot pay

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#95]
![image](https://user-images.githubusercontent.com/39575926/42058125-6d1dee52-7aed-11e8-9669-bd90ff17c07e.png)

When I click on the link to pay I get no button to pay with.   
http://rams.test.furfest.org/rams/art_show_applications/edit?id=cce19996-3787-4a5e-aeab-5948f1233a54 
![image](https://user-images.githubusercontent.com/39575926/42058187-9e60874a-7aed-11e8-9e13-603af429771b.png)

**Comment by kitsuta** [comment]
Related to https://github.com/MidwestFurryFandom/art_show/issues/83 -- I messed up some of the templating code in an earlier change. Should be fixed once https://github.com/MidwestFurryFandom/art_show/pull/91 gets merged and deployed.
