### ISSUE TITLE
Assign New agent Button does nothing 

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#96]
http://rams.test.furfest.org/rams/art_show_admin/form?id=cce19996-3787-4a5e-aeab-5948f1233a54

**Comment by kitsuta** [comment]
Ah, the form's HTML tag is wrong on this page. Until a fix gets put up, you can use the button on the attendee's edit page by clicking on the payment link from that form.

**Comment by Hugmonster** [comment]
Thanks
